/*
 * Created on 29 Jan 2016 ( Time 20:42:46 ) Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite)

package com.aqitrade.arcus.data.entity;

import java.io.Serializable;

// import javax.validation.constraints.* ;
// import org.hibernate.validator.constraints.* ;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "application"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "application", catalog = "arcus")
// Define named queries here
@NamedQueries({@NamedQuery(name = "ApplicationEntity.countAll",
    query = "SELECT COUNT(x) FROM ApplicationEntity x")})
@Cacheable(true)
public class ApplicationEntity implements Serializable {

  private static final long serialVersionUID = 1L;

  // ----------------------------------------------------------------------
  // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
  // ----------------------------------------------------------------------
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "application_id", nullable = false)
  private Integer applicationId;


  // ----------------------------------------------------------------------
  // ENTITY DATA FIELDS
  // ----------------------------------------------------------------------
  @Column(name = "name", nullable = false, length = 45)
  private String name;

  // "applicationGroupId" (column "application_group_id") is not defined by itself because used as
  // FK in a link


  // ----------------------------------------------------------------------
  // ENTITY LINKS ( RELATIONSHIP )
  // ----------------------------------------------------------------------
  @ManyToOne
  @JoinColumn(name = "application_group_id", referencedColumnName = "application_group_id")
  private ApplicationGroupEntity applicationGroup;


  // ----------------------------------------------------------------------
  // CONSTRUCTOR(S)
  // ----------------------------------------------------------------------
  public ApplicationEntity() {
    super();
  }

  // ----------------------------------------------------------------------
  // GETTER & SETTER FOR THE KEY FIELD
  // ----------------------------------------------------------------------
  public void setApplicationId(Integer applicationId) {
    this.applicationId = applicationId;
  }

  public Integer getApplicationId() {
    return this.applicationId;
  }

  // ----------------------------------------------------------------------
  // GETTERS & SETTERS FOR FIELDS
  // ----------------------------------------------------------------------
  // --- DATABASE MAPPING : name ( VARCHAR )
  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }


  // ----------------------------------------------------------------------
  // GETTERS & SETTERS FOR LINKS
  // ----------------------------------------------------------------------
  public void setApplicationGroup(ApplicationGroupEntity applicationGroup) {
    this.applicationGroup = applicationGroup;
  }

  public ApplicationGroupEntity getApplicationGroup() {
    return this.applicationGroup;
  }


  // ----------------------------------------------------------------------
  // toString METHOD
  // ----------------------------------------------------------------------
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append("[");
    sb.append(applicationId);
    sb.append("]:");
    sb.append(name);
    return sb.toString();
  }

}
