/*
 * Created on 29 Jan 2016 ( Time 20:42:46 ) Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite)

package com.aqitrade.arcus.data.entity;

import java.io.Serializable;

// import javax.validation.constraints.* ;
// import org.hibernate.validator.constraints.* ;

import javax.persistence.*;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Persistent class for entity stored in table "broker"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "broker", catalog = "arcus")
// Define named queries here
@NamedQueries({
    @NamedQuery(name = "BrokerEntity.countAll", query = "SELECT COUNT(x) FROM BrokerEntity x")})
@Cacheable(true)
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)

public class BrokerEntity implements Serializable {

  private static final long serialVersionUID = 1L;

  // ----------------------------------------------------------------------
  // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
  // ----------------------------------------------------------------------
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "broker_id", nullable = false)
  private Integer brokerId;


  // ----------------------------------------------------------------------
  // ENTITY DATA FIELDS
  // ----------------------------------------------------------------------
  @Column(name = "broker_name", nullable = false, length = 45)
  private String brokerName;



  // ----------------------------------------------------------------------
  // ENTITY LINKS ( RELATIONSHIP )
  // ----------------------------------------------------------------------

  // ----------------------------------------------------------------------
  // CONSTRUCTOR(S)
  // ----------------------------------------------------------------------
  public BrokerEntity() {
    super();
  }

  // ----------------------------------------------------------------------
  // GETTER & SETTER FOR THE KEY FIELD
  // ----------------------------------------------------------------------
  public void setBrokerId(Integer brokerId) {
    this.brokerId = brokerId;
  }

  public Integer getBrokerId() {
    return this.brokerId;
  }

  // ----------------------------------------------------------------------
  // GETTERS & SETTERS FOR FIELDS
  // ----------------------------------------------------------------------
  // --- DATABASE MAPPING : broker_name ( VARCHAR )
  public void setBrokerName(String brokerName) {
    this.brokerName = brokerName;
  }

  public String getBrokerName() {
    return this.brokerName;
  }


  // ----------------------------------------------------------------------
  // GETTERS & SETTERS FOR LINKS
  // ----------------------------------------------------------------------

  // ----------------------------------------------------------------------
  // toString METHOD
  // ----------------------------------------------------------------------
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append("[");
    sb.append(brokerId);
    sb.append("]:");
    sb.append(brokerName);
    return sb.toString();
  }

}
