/*
 * Created on 31 Jan 2016 ( Time 10:54:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.aqitrade.arcus.data.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "portfolio_application"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="portfolio_application", catalog="arcus" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PortfolioApplicationEntity.countAll", query="SELECT COUNT(x) FROM PortfolioApplicationEntity x" )
} )
public class PortfolioApplicationEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="portfolio_application", nullable=false)
    private Integer    portfolioApplication ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	// "portfolioId" (column "portfolio_id") is not defined by itself because used as FK in a link 
	// "applicationId" (column "application_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="application_id", referencedColumnName="application_id")
    private ApplicationEntity application ;

    @ManyToOne
    @JoinColumn(name="portfolio_id", referencedColumnName="portfolio_id")
    private PortfolioEntity portfolio   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PortfolioApplicationEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPortfolioApplication( Integer portfolioApplication ) {
        this.portfolioApplication = portfolioApplication ;
    }
    public Integer getPortfolioApplication() {
        return this.portfolioApplication;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setApplication( ApplicationEntity application ) {
        this.application = application;
    }
    public ApplicationEntity getApplication() {
        return this.application;
    }

    public void setPortfolio( PortfolioEntity portfolio ) {
        this.portfolio = portfolio;
    }
    public PortfolioEntity getPortfolio() {
        return this.portfolio;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(portfolioApplication);
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
