/*
 * Created on 31 Jan 2016 ( Time 10:54:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.aqitrade.arcus.data.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "portfolio_application"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="portfolio_application", catalog="arcus" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PortfolioApplicationEntity.countAll", query="SELECT COUNT(x) FROM PortfolioApplicationEntity x" )
} )
public class PortfolioApplicationEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="portfolio_application", nullable=false)
    private Integer    portfolioApplicationId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	// "portfolioId" (column "portfolio_id") is not defined by itself because used as FK in a link 
	// "applicationId" (column "application_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @Column(name="application_id", nullable=false)
    private Integer applicationId;

    @Column(name="portfolio_id", nullable=false)
    private Integer portfolioId   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PortfolioApplicationEntity() {
		super();
    }


    /**
     * @return the portfolioApplicationId
     */
    public Integer getPortfolioApplicationId() {
      return portfolioApplicationId;
    }


    /**
     * @param portfolioApplicationId the portfolioApplicationId to set
     */
    public void setPortfolioApplicationId(Integer portfolioApplicationId) {
      this.portfolioApplicationId = portfolioApplicationId;
    }


    /**
     * @return the applicationId
     */
    public Integer getApplicationId() {
      return applicationId;
    }


    /**
     * @param applicationId the applicationId to set
     */
    public void setApplicationId(Integer applicationId) {
      this.applicationId = applicationId;
    }


    /**
     * @return the portfolioId
     */
    public Integer getPortfolioId() {
      return portfolioId;
    }


    /**
     * @param portfolioId the portfolioId to set
     */
    public void setPortfolioId(Integer portfolioId) {
      this.portfolioId = portfolioId;
    }
    
  

}
