/*
 * Created on 31 Jan 2016 ( Time 11:37:05 ) Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.aqitrade.arcus.data.entity;

import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "UserPreferenceEntity" ( stored in table "user_preference" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class UserPreferenceEntityKey implements Serializable {
  private static final long serialVersionUID = 1L;

  // ----------------------------------------------------------------------
  // ENTITY KEY ATTRIBUTES
  // ----------------------------------------------------------------------
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "user_id", nullable = false)
  private Long userId;

  @Column(name = "preference_key", nullable = false, length = 255)
  private String preferenceKey;


  // ----------------------------------------------------------------------
  // CONSTRUCTORS
  // ----------------------------------------------------------------------
  public UserPreferenceEntityKey() {
    super();
  }

  public UserPreferenceEntityKey(Long userId, String preferenceKey) {
    super();
    this.userId = userId;
    this.preferenceKey = preferenceKey;
  }

  // ----------------------------------------------------------------------
  // GETTERS & SETTERS FOR KEY FIELDS
  // ----------------------------------------------------------------------
  public void setUserId(Long value) {
    this.userId = value;
  }

  public Long getUserId() {
    return this.userId;
  }

  public void setPreferenceKey(String value) {
    this.preferenceKey = value;
  }

  public String getPreferenceKey() {
    return this.preferenceKey;
  }


  // ----------------------------------------------------------------------
  // equals METHOD
  // ----------------------------------------------------------------------
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (this.getClass() != obj.getClass())
      return false;
    UserPreferenceEntityKey other = (UserPreferenceEntityKey) obj;
    // --- Attribute userId
    if (userId == null) {
      if (other.userId != null)
        return false;
    } else if (!userId.equals(other.userId))
      return false;
    // --- Attribute preferenceKey
    if (preferenceKey == null) {
      if (other.preferenceKey != null)
        return false;
    } else if (!preferenceKey.equals(other.preferenceKey))
      return false;
    return true;
  }


  // ----------------------------------------------------------------------
  // hashCode METHOD
  // ----------------------------------------------------------------------
  public int hashCode() {
    final int prime = 31;
    int result = 1;

    // --- Attribute userId
    result = prime * result + ((userId == null) ? 0 : userId.hashCode());
    // --- Attribute preferenceKey
    result = prime * result + ((preferenceKey == null) ? 0 : preferenceKey.hashCode());

    return result;
  }


  // ----------------------------------------------------------------------
  // toString METHOD
  // ----------------------------------------------------------------------
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append(userId);
    sb.append("|");
    sb.append(preferenceKey);
    return sb.toString();
  }
}
